---
title: "glinski_dehydration"
output: html_document
---
tested hypotheses
============
list

things to do
============
list

general configuration
=====================
Install and load supporting libraries.
```{r eval=TRUE, echo=FALSE}
print(Sys.info()[4])

R.Version()$version.string
library(rmarkdown, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
library(knitr, quietly = TRUE, warn.conflicts = FALSE)
print("list of loaded packages: ")
print((.packages()))
```

import experimental exposure and dehydration data
=================================
Load csv file with experimental dehydration data. The below may return false but still be OK if rstudio does not have privileges to data directory (e.g., attached drive).

```{r eval=TRUE, echo=FALSE}
if(Sys.info()[4]=="DONNA-PC"){
  dehyd.root <- path.expand("C:/Users/Donna/Documents/Github/glinski_metabolites/")
}

if(Sys.info()[4]=="stp-air-3.local" || Sys.info()[4]=="stp-air.local" || Sys.info()[4]=="stp-air"){
  dehyd.root <- path.expand("~/git/glinski_dehydration/")
}

if(Sys.info()[4]=="DZ2626UTPURUCKE"){
  dehyd.root <- "k:/git/glinski_metabolites/"
}
print(paste("Root directory location: ", dehyd.root, sep=""))

dehyd.csv.in <- paste(dehyd.root, "csv_in/", sep="")
dehyd.csv.out <- paste(dehyd.root, "csv_out/", sep="")
dehyd.graphics <- paste(dehyd.root, "graphics/", sep="")
dehyd.tables <- paste(dehyd.root, "tables/", sep="")

#maybe ok even if remote drive returns false
print(paste("check to see if R can access files OK: ", file.exists(dehyd.csv.in), sep = ""))

#original excel file has some amphibi as matrix instead aof amphib
dehyd <- read.table(paste(dehyd.csv.in,"dehydration.csv",sep=""), header = TRUE, sep = ",")
```

dehydration exposure data structure
====================================
Check out structure of imported data sets. 

```{r data_structure, eval=TRUE, echo=TRUE}
str(dehyd)
unique(dehyd$parent)
unique(dehyd$analyte)
unique(dehyd$matrix)
unique(dehyd$species)
#View(dehyd)

dehyd.amphib <- dehyd[which(dehyd$matrix=="amphib"),]
dehyd.soil <- dehyd[which(dehyd$matrix=="soil"),]

#atrazine
dehyd.amphib.atrazine <- dehyd.amphib[which(dehyd.amphib$parent=="atrazine"),]
dehyd.amphib.atrazine.atrazine <-   dehyd.amphib.atrazine[which(dehyd.amphib.atrazine$analyte=="atrazine"),]
dehyd.amphib.atrazine.dea <-   dehyd.amphib.atrazine[which(dehyd.amphib.atrazine$analyte=="dea"),]
dehyd.amphib.atrazine.dia <-   dehyd.amphib.atrazine[which(dehyd.amphib.atrazine$analyte=="dia"),]
#chlorothalonil
dehyd.amphib.chloro <- dehyd.amphib[which(dehyd.amphib$parent=="chloro"),]
dehyd.amphib.chloro.chloro <- dehyd.amphib.chloro[which(dehyd.amphib.chloro$analyte=="chloro"),]
dehyd.amphib.chloro.chloromet <- dehyd.amphib.chloro[which(dehyd.amphib.chloro$analyte=="chloromet"),]
#imidacloprid
dehyd.amphib.imid <- dehyd.amphib[which(dehyd.amphib$parent=="imid"),]
dehyd.amphib.imid.imid <- dehyd.amphib.imid[which(dehyd.amphib.imid$analyte=="imid"),]
#metolachlor
dehyd.amphib.metol <- dehyd.amphib[which(dehyd.amphib$parent=="metol"),]
dehyd.amphib.metol.metol <- dehyd.amphib.metol[which(dehyd.amphib.metol$analyte=="metol"),]
dehyd.amphib.metol.mesa <- dehyd.amphib.metol[which(dehyd.amphib.metol$analyte=="mesa"),]
dehyd.amphib.metol.moxa <- dehyd.amphib.metol[which(dehyd.amphib.metol$analyte=="moxa"),]
#tridimefon
dehyd.amphib.tdn <- dehyd.amphib[which(dehyd.amphib$parent=="tdn"),]
dehyd.amphib.tdn.tdn <- dehyd.amphib.tdn[which(dehyd.amphib.tdn$analyte=="tdn"),]
dehyd.amphib.tdn.tdla <- dehyd.amphib.tdn[which(dehyd.amphib.tdn$analyte=="tdla"),]
dehyd.amphib.tdn.tdlb <- dehyd.amphib.tdn[which(dehyd.amphib.tdn$analyte=="tdlb"),]
```

